@startgantt
Project starts the 2025-05-01

[Analyse des besoins] lasts 10 days
[Conception] starts at [Analyse des besoins]'s end and lasts 15 days
[Développement Frontend] starts at [Conception]'s end and lasts 30 days
[Développement Backend] starts at [Conception]'s end and lasts 30 days
[Tests et validation] starts at [Développement Frontend]'s end and ends at [Développement Backend]'s end
[Déploiement] starts at [Tests et validation]'s end and lasts 20 days
[Maintenance] starts at [Déploiement]'s end and lasts 60 days

@endgantt
