@startuml
left to right direction

actor Admin
actor Employee

usecase (Authentication) as UC_Auth #right

rectangle "Admin Use Cases" {
  usecase (Create User) as UC_CreateUser
  usecase (Update User) as UC_UpdateUser
  usecase (Delete User) as UC_DeleteUser
  usecase (Create Employee) as UC_CreateEmployee
  usecase (Update Employee) as UC_UpdateEmployee
  usecase (Delete Employee) as UC_DeleteEmployee
  usecase (Create Department) as UC_CreateDepartment
  usecase (Update Department) as UC_UpdateDepartment
  usecase (Delete Department) as UC_DeleteDepartment
  usecase (Create Project) as UC_CreateProject
  usecase (Update Project) as UC_UpdateProject
  usecase (Delete Project) as UC_DeleteProject
}

rectangle "Employee Use Cases" {
  usecase (View Profile) as UC_ViewProfile
  usecase (View Employee Details) as UC_ViewEmployee
  usecase (View Department) as UC_ViewDepartment
  usecase (View Project) as UC_ViewProject
}

Admin --> UC_Auth
Employee --> UC_Auth

Admin --> UC_CreateUser
Admin --> UC_UpdateUser
Admin --> UC_DeleteUser
Admin --> UC_CreateEmployee
Admin --> UC_UpdateEmployee
Admin --> UC_DeleteEmployee
Admin --> UC_CreateDepartment
Admin --> UC_UpdateDepartment
Admin --> UC_DeleteDepartment
Admin --> UC_CreateProject
Admin --> UC_UpdateProject
Admin --> UC_DeleteProject

Employee --> UC_ViewProfile
Employee --> UC_ViewEmployee
Employee --> UC_ViewDepartment
Employee --> UC_ViewProject

UC_Auth <|-- UC_CreateUser
UC_Auth <|-- UC_UpdateUser
UC_Auth <|-- UC_DeleteUser
UC_Auth <|-- UC_ViewProfile
UC_Auth <|-- UC_CreateEmployee
UC_Auth <|-- UC_UpdateEmployee
UC_Auth <|-- UC_DeleteEmployee
UC_Auth <|-- UC_ViewEmployee
UC_Auth <|-- UC_CreateDepartment
UC_Auth <|-- UC_UpdateDepartment
UC_Auth <|-- UC_DeleteDepartment
UC_Auth <|-- UC_ViewDepartment
UC_Auth <|-- UC_CreateProject
UC_Auth <|-- UC_UpdateProject
UC_Auth <|-- UC_DeleteProject
UC_Auth <|-- UC_ViewProject

@enduml
